### ISSUE TITLE
storing_pretty_json doesn't seem to work with messagehub plugin

### ISSUE THREAD

**Issue by gsr-shanks** [RHQE/metamorph#10]
I tried to run plugins/morph_messagehub.py env --env-variable CI_MESSAGE, however the data in metamorph.json is not pretty printed. Please check: https://url.corp.redhat.com/e0522a0

**Comment by Jurisak** [comment]
@gsr-shanks I'm unalbe to acces mentioned url.

**Comment by gsr-shanks** [comment]
It should be accessible now.
