### ISSUE TITLE
morph_resultsdb does not create 'metamorph' as root element.

### ISSUE THREAD

**Issue by gsr-shanks** [RHQE/metamorph#8]
plugins/morph_resultsdb.py does not create 'metamorph' as root element if executed first. This should be true for any plugin.

**Comment by Jurisak** [comment]
Solved in #7

**Comment by gsr-shanks** [comment]
It is not solved for morph_resultsdb yet.

**Comment by Jurisak** [comment]
I see it as solved for morph_resultsdb.py. Could you please more describe the problem which you have?

**Comment by gsr-shanks** [comment]
I am unable to query using NVR kernel-pegas-4.10.09.el7, could you please give me another NVR that works ?

**Comment by Jurisak** [comment]
kernel-3.10.0-656.el7  but I'm able to query kernel-pegas-4.10.09.el7 as well.

**Comment by gsr-shanks** [comment]
Ok, I tried with kernel-3.10.0-656.el7 and don't see metamorph as root element.

This is what I did:
git clone https://github.com/Jurisak/metamorph.git
cd metamorph/
git checkout -b Jurisak-pdc-support master
git pull https://github.com/Jurisak/metamorph.git pdc-support
python setup.py install

python ~/metamorph/metamorph/plugins/morph_resultsdb.py --resultsdb-api-url https://resultsdb.com/api/v2.0/results  --test-tier 1 --nvr kernel-3.10.0-656.el7


Check metamorph.json

**Comment by gsr-shanks** [comment]
```
[root@04e64ef49e86 metamorph]# less metamorph.json 

{
  "results": {
    "tier": {
      "ci_tier": "1", 
      "tier_tag": false, 
      "job_name": [
        {
```

**Comment by Jurisak** [comment]
:D my result: 
`{
  "metamorph": {
    "resultsdb": {
      "results": {
        "tier": {
          "job_name": [`

Please check morph_resultsd.py whether it imports support_functions and not logging_support.
Please check whether lib/support_functions.py contains storing_pretty_json() which appends.

**Comment by gsr-shanks** [comment]
Yes, it imports right: from metamorph.lib.support_functions import setup_logging, storing_pretty_json


And yes, I see that storing_pretty_json() exists.

**Comment by gsr-shanks** [comment]
Could you try the command I pasted above ?

**Comment by Jurisak** [comment]
Above example is from: 
`python3 plugins/morph_resultsdb.py --test-tier 1 --nvr kernel-3.10.0-656.el7  --resultsdb-api-url https://resultsdb.com/api/v2.0/results?`

**Comment by gsr-shanks** [comment]
I mean starting from git clone :-)

**Comment by Jurisak** [comment]
I'll do.
What comes in my mind is your execution of morph_resultsdb: 
`~/metamorph/metamorph/` 
I do not know what is your directory structure but you could possibly run different metamorph directory.

**Comment by Jurisak** [comment]
What i did:
$mkdir tmp
$cd tmp
$git clone https://github.com/Jurisak/metamorph.git
Cloning into 'metamorph'...
remote: Counting objects: 415, done.
remote: Compressing objects: 100% (227/227), done.
remote: Total 415 (delta 125), reused 0 (delta 0), pack-reused 185
Receiving objects: 100% (415/415), 76.77 KiB | 73.00 KiB/s, done.
Resolving deltas: 100% (206/206), done.
Checking connectivity... done.

$cd metamorph/
$git checkout -b Jurisak-pdc-support master
Switched to a new branch 'Jurisak-pdc-support'
$ git pull https://github.com/Jurisak/metamorph.git pdc-support
# python3 setup.py install

$ python3 metamorph/plugins/morph_resultsdb.py --test-tier 1 --nvr kernel-3.10.0-656.el7  --resultsdb-api-url https://resultsdb.com/api/v2.0/results?

result:
{
  "metamorph": {
    "resultsdb": {
      "results": {
        "tier": {
          "job_name": [
            {

**Comment by gsr-shanks** [comment]
I see it now. Thanks. Not sure what was wrong.
